export type Platform = "instagram" | "tiktok" | "both";
export type ContentCategory =
  | "quotes"
  | "stories"
  | "devotionals"
  | "engagement"
  | "creative";

export interface ContentItem {
  id: string;
  date: string; // YYYY-MM-DD
  title: string;
  series: string;
  category: ContentCategory;
  platform: Platform;
  description: string;
  caption: string;
  hashtags: string;
  bibleRef?: string;
  notes?: string;
}

const APRIL_2026: ContentItem[] = [
  // === APRIL 1 (Wednesday) ===
  {
    id: "apr-01-verse",
    date: "2026-04-01",
    title: "Verse of the Day: New Beginnings",
    series: "Daily Verse of the Day",
    category: "quotes",
    platform: "both",
    description: "Start April with a verse about God making all things new. Clean, elegant verse card.",
    caption: "A new month, a new mercy. God is doing something new in your life.\n\n\"See, I am doing a new thing! Now it springs up; do you not perceive it?\" — Isaiah 43:19\n\nWhat are you trusting God for this April? Drop it below.",
    hashtags: "#LivingWater #VerseOfTheDay #Isaiah4319 #NewBeginnings #BibleVerse #Faith #ChristianContent",
    bibleRef: "Isaiah 43:19",
  },
  {
    id: "apr-01-word",
    date: "2026-04-01",
    title: "Word Study: Chesed (Steadfast Love)",
    series: "Word Study Wednesday",
    category: "devotionals",
    platform: "both",
    description: "Deep dive into the Hebrew word 'Chesed' — God's steadfast, covenant love. Use a text-overlay reel/carousel.",
    caption: "WORD STUDY: CHESED\n\nThe Hebrew word 'Chesed' (חֶסֶד) means steadfast love, mercy, and faithfulness. It's the word used over 240 times in the Old Testament to describe God's loyal, covenant love for His people.\n\nIt's not just love — it's love that refuses to let go.\n\n\"Give thanks to the Lord, for He is good. His chesed endures forever.\" — Psalm 136:1\n\nGod's love for you is not fragile. It endures.",
    hashtags: "#LivingWater #WordStudy #Chesed #HebrewWord #GodsLove #Psalm136 #BiblicalHebrew #ChristianTeaching",
    bibleRef: "Psalm 136:1",
  },

  // === APRIL 2 (Thursday) ===
  {
    id: "apr-02-verse",
    date: "2026-04-02",
    title: "Verse of the Day: Trust in the Lord",
    series: "Daily Verse of the Day",
    category: "quotes",
    platform: "both",
    description: "Classic Proverbs verse on trust. Simple, clean verse card with a nature background.",
    caption: "Stop leaning on your own understanding.\n\n\"Trust in the Lord with all your heart and lean not on your own understanding; in all your ways submit to Him, and He will make your paths straight.\" — Proverbs 3:5-6\n\nHe knows the way even when you don't.",
    hashtags: "#LivingWater #VerseOfTheDay #Proverbs3 #TrustGod #Faith #BibleVerse #ChristianLife",
    bibleRef: "Proverbs 3:5-6",
  },
  {
    id: "apr-02-character",
    date: "2026-04-02",
    title: "Biblical Character: Moses — Called from the Burning Bush",
    series: "Biblical Character Series",
    category: "stories",
    platform: "both",
    description: "Short narrative reel/carousel about Moses — from murderer to deliverer. Focus on God using imperfect people.",
    caption: "MOSES: The Reluctant Leader\n\nHe was a prince who became a fugitive. A shepherd who became a deliverer. A man who said \"I can't speak\" — and then spoke to Pharaoh.\n\nGod didn't call Moses because he was ready. God called him because He was ready.\n\nIf God is calling you today, don't look at your weakness. Look at His strength.\n\n\"Who gave human beings their mouths? Is it not I, the Lord? Now go; I will help you speak.\" — Exodus 4:11-12",
    hashtags: "#LivingWater #Moses #BibleStory #BiblicalCharacter #Exodus #GodsCall #Faith #ChristianContent",
    bibleRef: "Exodus 4:11-12",
  },

  // === APRIL 3 (Friday) ===
  {
    id: "apr-03-verse",
    date: "2026-04-03",
    title: "Verse of the Day: Peace I Leave With You",
    series: "Daily Verse of the Day",
    category: "quotes",
    platform: "both",
    description: "Good Friday preparation — Jesus' words of peace. Solemn, beautiful design.",
    caption: "Before He went to the cross, He left us this:\n\n\"Peace I leave with you; my peace I give you. I do not give to you as the world gives. Do not let your hearts be troubled and do not be afraid.\" — John 14:27\n\nThe peace Jesus gives doesn't depend on your circumstances. It depends on His presence.",
    hashtags: "#LivingWater #VerseOfTheDay #John14 #PeaceOfChrist #GoodFriday #Easter #BibleVerse",
    bibleRef: "John 14:27",
    notes: "Good Friday is April 3. Tone should be reflective and reverent.",
  },
  {
    id: "apr-03-easter",
    date: "2026-04-03",
    title: "Easter Countdown: Good Friday — It Is Finished",
    series: "Seasonal Devotional Series",
    category: "creative",
    platform: "both",
    description: "Good Friday devotional. Dark, solemn design with the cross. Reel with ambient worship music and text overlay.",
    caption: "GOOD FRIDAY\n\nToday we remember the day love was nailed to a cross.\n\nJesus — the sinless Son of God — took our place. He bore our sin, our shame, our death.\n\n\"It is finished.\" — John 19:30\n\nThose three words changed everything. The debt is paid. The veil is torn. The way is open.\n\nToday, we mourn. But Sunday is coming.",
    hashtags: "#LivingWater #GoodFriday #Easter #ItIsFinished #TheCross #Jesus #John1930 #ChristianFaith",
    bibleRef: "John 19:30",
  },

  // === APRIL 4 (Saturday) ===
  {
    id: "apr-04-verse",
    date: "2026-04-04",
    title: "Verse of the Day: Be Still",
    series: "Daily Verse of the Day",
    category: "quotes",
    platform: "both",
    description: "Holy Saturday — a day of silence and waiting. Minimalist verse card.",
    caption: "In the silence between Friday and Sunday, we wait.\n\n\"Be still, and know that I am God.\" — Psalm 46:10\n\nSometimes God asks us to wait in the dark. Not because He's absent — but because He's working.",
    hashtags: "#LivingWater #VerseOfTheDay #Psalm46 #BeStill #HolySaturday #Easter #WaitOnGod",
    bibleRef: "Psalm 46:10",
    notes: "Holy Saturday. Keep it quiet and reflective.",
  },
  {
    id: "apr-04-psalm",
    date: "2026-04-04",
    title: "Psalms Spotlight: Psalm 22 — From Agony to Praise",
    series: "Psalms Spotlight",
    category: "quotes",
    platform: "both",
    description: "Psalm 22 — the psalm Jesus quoted on the cross. Show the prophetic connection to Good Friday.",
    caption: "PSALM SPOTLIGHT: Psalm 22\n\n\"My God, my God, why have you forsaken me?\" — Psalm 22:1\n\nDavid wrote these words 1,000 years before Christ. Yet they perfectly describe what happened on the cross.\n\nBut the Psalm doesn't end in despair. It ends in praise:\n\n\"All the ends of the earth will remember and turn to the Lord.\" — Psalm 22:27\n\nEven in the darkest moments, God's story leads to redemption.",
    hashtags: "#LivingWater #PsalmSpotlight #Psalm22 #Easter #Prophecy #TheCross #BibleStudy",
    bibleRef: "Psalm 22:1, 27",
  },

  // === APRIL 5 (Sunday — EASTER) ===
  {
    id: "apr-05-verse",
    date: "2026-04-05",
    title: "Verse of the Day: He Is Risen!",
    series: "Daily Verse of the Day",
    category: "quotes",
    platform: "both",
    description: "EASTER SUNDAY! Bright, joyful, celebratory verse card. Gold and white tones.",
    caption: "HE IS RISEN!\n\n\"He is not here; He has risen, just as He said!\" — Matthew 28:6\n\nThe tomb is empty. Death is defeated. Hope is alive.\n\nHappy Easter, family! Today we celebrate the greatest victory in history — our Savior lives!",
    hashtags: "#LivingWater #Easter #HeIsRisen #Matthew28 #Resurrection #JesusIsAlive #HappyEaster #ChristianFaith",
    bibleRef: "Matthew 28:6",
    notes: "EASTER SUNDAY — biggest post of the month. Maximum effort on design.",
  },
  {
    id: "apr-05-easter",
    date: "2026-04-05",
    title: "Easter Devotional: The Resurrection Changes Everything",
    series: "Seasonal Devotional Series",
    category: "creative",
    platform: "both",
    description: "Full Easter celebration reel. Sunrise footage, worship music, powerful text overlay about the resurrection.",
    caption: "EASTER SUNDAY\n\nFriday — He was crucified.\nSaturday — He lay in the tomb.\nSunday — HE ROSE.\n\n\"Where, O death, is your victory? Where, O death, is your sting?\" — 1 Corinthians 15:55\n\nBecause He lives, we can face tomorrow. Because He lives, every fear is gone. Because He lives, life is worth living.\n\nJesus Christ is alive. And because of that — so are we.\n\nHappy Resurrection Sunday!",
    hashtags: "#LivingWater #Easter #ResurrectionSunday #HeIsRisen #1Corinthians15 #JesusLives #GoodNews #ChristianContent",
    bibleRef: "1 Corinthians 15:55",
  },

  // === APRIL 6 (Monday) ===
  {
    id: "apr-06-verse",
    date: "2026-04-06",
    title: "Verse of the Day: By Grace You Are Saved",
    series: "Daily Verse of the Day",
    category: "quotes",
    platform: "both",
    description: "Post-Easter Monday — the Gospel in one verse. Elegant card.",
    caption: "The Gospel in one verse:\n\n\"For it is by grace you have been saved, through faith — and this is not from yourselves, it is the gift of God.\" — Ephesians 2:8\n\nYou can't earn it. You can't lose it. It's a gift. Receive it.",
    hashtags: "#LivingWater #VerseOfTheDay #Ephesians2 #Grace #Gospel #Salvation #BibleVerse #Faith",
    bibleRef: "Ephesians 2:8",
  },
  {
    id: "apr-06-gospel",
    date: "2026-04-06",
    title: "Good News Monday: The Core of the Gospel",
    series: "Good News Monday",
    category: "devotionals",
    platform: "both",
    description: "Start the week with the heart of the Gospel. Simple, clear, powerful.",
    caption: "GOOD NEWS MONDAY\n\nThe Gospel is simple:\n\n1. We all sinned and fell short of God's glory (Romans 3:23)\n2. The wages of sin is death (Romans 6:23)\n3. But God demonstrated His love — while we were still sinners, Christ died for us (Romans 5:8)\n4. If you confess with your mouth that Jesus is Lord and believe He rose from the dead, you will be saved (Romans 10:9)\n\nThis is the Good News. It's free. It's for you. Today.",
    hashtags: "#LivingWater #GoodNewsMonday #Gospel #Jesus #Salvation #Romans #GoodNews #Faith",
    bibleRef: "Romans 10:9",
  },

  // === APRIL 7 (Tuesday) ===
  {
    id: "apr-07-verse",
    date: "2026-04-07",
    title: "Verse of the Day: Jeremiah 29:11",
    series: "Daily Verse of the Day",
    category: "quotes",
    platform: "both",
    description: "Hope-filled verse. Warm tones.",
    caption: "God has a plan for you — and it's good.\n\n\"For I know the plans I have for you, declares the Lord, plans to prosper you and not to harm you, plans to give you hope and a future.\" — Jeremiah 29:11\n\nEven when you can't see the road ahead, He can.",
    hashtags: "#LivingWater #VerseOfTheDay #Jeremiah2911 #GodsPlans #Hope #Faith #BibleVerse",
    bibleRef: "Jeremiah 29:11",
  },
  {
    id: "apr-07-testimony",
    date: "2026-04-07",
    title: "Testimony Tuesday: From Doubt to Faith",
    series: "Testimony Tuesday",
    category: "stories",
    platform: "both",
    description: "Share the story of Thomas the disciple — doubting, then believing. Relatable testimony format.",
    caption: "TESTIMONY TUESDAY: Thomas\n\nThey told him Jesus was alive. He said: \"Unless I see the nail marks in His hands, I will not believe.\" (John 20:25)\n\nA week later, Jesus appeared and said: \"Put your finger here; see my hands. Stop doubting and believe.\" (John 20:27)\n\nThomas replied: \"My Lord and my God!\"\n\nJesus said: \"Blessed are those who have not seen and yet have believed.\"\n\nIf you're wrestling with doubt — you're in good company. Bring your doubts to Jesus. He's not afraid of them.",
    hashtags: "#LivingWater #TestimonyTuesday #Thomas #Doubt #Faith #John20 #Jesus #ChristianTestimony",
    bibleRef: "John 20:25-29",
  },

  // === APRIL 8 (Wednesday) ===
  {
    id: "apr-08-verse",
    date: "2026-04-08",
    title: "Verse of the Day: The Lord is My Shepherd",
    series: "Daily Verse of the Day",
    category: "quotes",
    platform: "both",
    description: "Psalm 23 opening verse. Peaceful pastoral design.",
    caption: "You are not wandering alone.\n\n\"The Lord is my shepherd, I lack nothing.\" — Psalm 23:1\n\nThe Good Shepherd leads, provides, protects, and restores. Whatever you need today — He is enough.",
    hashtags: "#LivingWater #VerseOfTheDay #Psalm23 #GoodShepherd #GodsProvision #BibleVerse #Peace",
    bibleRef: "Psalm 23:1",
  },
  {
    id: "apr-08-word",
    date: "2026-04-08",
    title: "Word Study: Shalom (Peace)",
    series: "Word Study Wednesday",
    category: "devotionals",
    platform: "both",
    description: "Explore 'Shalom' — not just peace, but wholeness, completeness, welfare. Text overlay reel.",
    caption: "WORD STUDY: SHALOM\n\nThe Hebrew word 'Shalom' (שָׁלוֹם) is often translated as 'peace' — but it means so much more.\n\nShalom means:\n- Completeness\n- Wholeness\n- Welfare\n- Harmony\n- Flourishing\n\nWhen God gives you peace, He's not just removing conflict. He's restoring everything to the way it was meant to be.\n\n\"The Lord gives strength to His people; the Lord blesses His people with shalom.\" — Psalm 29:11",
    hashtags: "#LivingWater #WordStudy #Shalom #Peace #HebrewWord #Psalm29 #BiblicalPeace #ChristianTeaching",
    bibleRef: "Psalm 29:11",
  },

  // === APRIL 9 (Thursday) ===
  {
    id: "apr-09-verse",
    date: "2026-04-09",
    title: "Verse of the Day: God Is Love",
    series: "Daily Verse of the Day",
    category: "quotes",
    platform: "both",
    description: "Simple, powerful statement. Warm red/gold card.",
    caption: "Three words that change everything:\n\n\"God is love.\" — 1 John 4:8\n\nNot God has love. Not God shows love sometimes. GOD IS LOVE. It's His nature. It's who He is. And He loves you.",
    hashtags: "#LivingWater #VerseOfTheDay #1John4 #GodIsLove #Love #BibleVerse #ChristianFaith",
    bibleRef: "1 John 4:8",
  },
  {
    id: "apr-09-fruit",
    date: "2026-04-09",
    title: "Fruit of the Spirit: Love",
    series: "Fruit of the Spirit Series",
    category: "devotionals",
    platform: "both",
    description: "Part 1 of the Fruit of the Spirit series — LOVE. Carousel or reel with definition and application.",
    caption: "FRUIT OF THE SPIRIT: LOVE (Part 1/9)\n\n\"But the fruit of the Spirit is love...\" — Galatians 5:22\n\nLove is listed first because it's the foundation of everything.\n\nBiblical love isn't a feeling — it's a choice. It's patient, kind, not self-seeking (1 Cor 13:4-5). It looks like Jesus washing the feet of the man who would betray Him.\n\nHow to grow in love this week:\n- Pray for someone who frustrates you\n- Serve without expecting anything back\n- Forgive before being asked\n\nLove is the first fruit because it feeds all the rest.",
    hashtags: "#LivingWater #FruitOfTheSpirit #Love #Galatians5 #ChristianLiving #SpiritualGrowth #BibleStudy",
    bibleRef: "Galatians 5:22",
  },

  // === APRIL 10 (Friday) ===
  {
    id: "apr-10-verse",
    date: "2026-04-10",
    title: "Verse of the Day: Do Not Fear",
    series: "Daily Verse of the Day",
    category: "quotes",
    platform: "both",
    description: "Courage verse for the end of the week.",
    caption: "He said it over 365 times in the Bible — one for every day:\n\n\"Do not fear, for I am with you; do not be dismayed, for I am your God. I will strengthen you and help you; I will uphold you with my righteous right hand.\" — Isaiah 41:10\n\nWhatever you're afraid of today — He's bigger.",
    hashtags: "#LivingWater #VerseOfTheDay #Isaiah41 #DoNotFear #Courage #GodsPromise #BibleVerse",
    bibleRef: "Isaiah 41:10",
  },
  {
    id: "apr-10-worship",
    date: "2026-04-10",
    title: "Worship Song Reflection: What A Beautiful Name",
    series: "Worship Song Reflection",
    category: "creative",
    platform: "both",
    description: "Connect the lyrics of 'What A Beautiful Name' by Hillsong to Scripture. Audio clip + text overlay for TikTok.",
    caption: "WORSHIP REFLECTION: \"What A Beautiful Name\"\n\n\"What a beautiful Name it is, the Name of Jesus\"\n\n\"Therefore God exalted Him to the highest place and gave Him the name that is above every name.\" — Philippians 2:9\n\nThe Name of Jesus carries authority over every sickness, every fear, every stronghold. When you don't know what to pray — just whisper His Name.\n\nJesus. There is power in that Name.",
    hashtags: "#LivingWater #WorshipReflection #WhatABeautifulName #Hillsong #Philippians2 #JesusName #Worship",
    bibleRef: "Philippians 2:9",
  },

  // === APRIL 11 (Saturday) ===
  {
    id: "apr-11-verse",
    date: "2026-04-11",
    title: "Verse of the Day: Rest in Him",
    series: "Daily Verse of the Day",
    category: "quotes",
    platform: "both",
    description: "Sabbath rest verse. Calm, peaceful design.",
    caption: "It's okay to rest. Jesus invites you to:\n\n\"Come to me, all you who are weary and burdened, and I will give you rest.\" — Matthew 11:28\n\nYou don't have to carry it all. Lay it down at His feet today.",
    hashtags: "#LivingWater #VerseOfTheDay #Matthew11 #Rest #ComeToJesus #BibleVerse #Peace",
    bibleRef: "Matthew 11:28",
  },
  {
    id: "apr-11-psalm",
    date: "2026-04-11",
    title: "Psalms Spotlight: Psalm 91 — Under His Wings",
    series: "Psalms Spotlight",
    category: "quotes",
    platform: "both",
    description: "Psalm 91 — God's protection. Powerful verses about dwelling in His shelter.",
    caption: "PSALM SPOTLIGHT: Psalm 91\n\n\"Whoever dwells in the shelter of the Most High will rest in the shadow of the Almighty.\" — Psalm 91:1\n\n\"He will cover you with his feathers, and under his wings you will find refuge.\" — Psalm 91:4\n\nThis Psalm is a fortress of promises. When the world feels unsafe, God is your shelter. You are hidden in Him.\n\nSave this for when you need a reminder that you are protected.",
    hashtags: "#LivingWater #PsalmSpotlight #Psalm91 #GodsProtection #Refuge #BibleStudy #Shelter",
    bibleRef: "Psalm 91:1, 4",
  },

  // === APRIL 12 (Sunday) ===
  {
    id: "apr-12-verse",
    date: "2026-04-12",
    title: "Verse of the Day: This Is the Day",
    series: "Daily Verse of the Day",
    category: "quotes",
    platform: "both",
    description: "Joyful Sunday verse. Bright, uplifting design.",
    caption: "Happy Sunday!\n\n\"This is the day that the Lord has made; let us rejoice and be glad in it.\" — Psalm 118:24\n\nToday is a gift. Worship Him with your whole heart.",
    hashtags: "#LivingWater #VerseOfTheDay #Psalm118 #Sunday #Rejoice #Worship #BibleVerse",
    bibleRef: "Psalm 118:24",
  },
  {
    id: "apr-12-memory",
    date: "2026-04-12",
    title: "Scripture Memory Challenge: Romans 8:28",
    series: "Scripture Memory Challenge",
    category: "engagement",
    platform: "both",
    description: "Weekly memory verse challenge. Post the verse, encourage followers to memorize it by next Sunday.",
    caption: "SCRIPTURE MEMORY CHALLENGE\n\nThis week's verse to memorize:\n\n\"And we know that in all things God works for the good of those who love Him, who have been called according to His purpose.\" — Romans 8:28\n\nChallenge: Memorize this verse by next Sunday. Write it on a sticky note. Say it out loud every morning.\n\nComment \"I'M IN\" if you're taking the challenge!",
    hashtags: "#LivingWater #ScriptureMemory #Romans828 #MemorizeScripture #BibleChallenge #ChristianCommunity",
    bibleRef: "Romans 8:28",
  },

  // === APRIL 13 (Monday) ===
  {
    id: "apr-13-verse",
    date: "2026-04-13",
    title: "Verse of the Day: New Creation",
    series: "Daily Verse of the Day",
    category: "quotes",
    platform: "both",
    description: "Identity in Christ verse.",
    caption: "Your past doesn't define you. Christ does.\n\n\"Therefore, if anyone is in Christ, the new creation has come: The old has gone, the new is here!\" — 2 Corinthians 5:17\n\nYou are not who you used to be. You are who God says you are.",
    hashtags: "#LivingWater #VerseOfTheDay #2Corinthians5 #NewCreation #IdentityInChrist #BibleVerse",
    bibleRef: "2 Corinthians 5:17",
  },
  {
    id: "apr-13-gospel",
    date: "2026-04-13",
    title: "Good News Monday: God So Loved the World",
    series: "Good News Monday",
    category: "devotionals",
    platform: "both",
    description: "The most famous verse in the Bible. Simple but powerful delivery.",
    caption: "GOOD NEWS MONDAY\n\n\"For God so loved the world that He gave His one and only Son, that whoever believes in Him shall not perish but have eternal life.\" — John 3:16\n\nGod. So. Loved. The. World.\n\nNot just the good people. Not just the religious people. The WORLD. That includes you — right where you are, right as you are.\n\nThis is the Good News. God's love is not earned. It's given.",
    hashtags: "#LivingWater #GoodNewsMonday #John316 #GodsLove #Gospel #GoodNews #Jesus #Salvation",
    bibleRef: "John 3:16",
  },

  // === APRIL 14 (Tuesday) ===
  {
    id: "apr-14-verse",
    date: "2026-04-14",
    title: "Verse of the Day: Strength in Weakness",
    series: "Daily Verse of the Day",
    category: "quotes",
    platform: "both",
    description: "Paul's testimony of God's sufficient grace.",
    caption: "Your weakness is not a disqualification. It's an invitation.\n\n\"My grace is sufficient for you, for my power is made perfect in weakness.\" — 2 Corinthians 12:9\n\nWhen you feel like you're not enough — that's exactly where God shows up.",
    hashtags: "#LivingWater #VerseOfTheDay #2Corinthians12 #Grace #Weakness #GodsStrength #BibleVerse",
    bibleRef: "2 Corinthians 12:9",
  },
  {
    id: "apr-14-testimony",
    date: "2026-04-14",
    title: "Testimony Tuesday: Ruth — Faithfulness in Loss",
    series: "Testimony Tuesday",
    category: "stories",
    platform: "both",
    description: "Ruth's story — loyalty, faith, and God's redemption through a foreign widow.",
    caption: "TESTIMONY TUESDAY: Ruth\n\nShe lost her husband. She was a foreigner. She had nothing.\n\nBut Ruth clung to Naomi and said: \"Where you go I will go, and where you stay I will stay. Your people will be my people and your God my God.\" — Ruth 1:16\n\nGod took a woman with nothing and placed her in the lineage of Jesus Christ.\n\nYour story isn't over. God can redeem anything — even your deepest loss.",
    hashtags: "#LivingWater #TestimonyTuesday #Ruth #BibleStory #Redemption #GodsGrace #Faith",
    bibleRef: "Ruth 1:16",
  },

  // === APRIL 15 (Wednesday) ===
  {
    id: "apr-15-verse",
    date: "2026-04-15",
    title: "Verse of the Day: Lamp to My Feet",
    series: "Daily Verse of the Day",
    category: "quotes",
    platform: "both",
    description: "Classic verse about God's Word as guidance.",
    caption: "You don't need to see the whole staircase — just the next step.\n\n\"Your word is a lamp for my feet, a light on my path.\" — Psalm 119:105\n\nGod doesn't always show you the destination. But He always lights the next step.",
    hashtags: "#LivingWater #VerseOfTheDay #Psalm119 #GodsWord #Guidance #Light #BibleVerse",
    bibleRef: "Psalm 119:105",
  },
  {
    id: "apr-15-word",
    date: "2026-04-15",
    title: "Word Study: Logos (The Word)",
    series: "Word Study Wednesday",
    category: "devotionals",
    platform: "both",
    description: "Greek word 'Logos' — the Word, divine reason, Jesus Himself. Connect to John 1:1.",
    caption: "WORD STUDY: LOGOS\n\nThe Greek word 'Logos' (λόγος) means 'word, reason, plan.' But in John 1, it means something far greater:\n\n\"In the beginning was the Logos, and the Logos was with God, and the Logos was God.\" — John 1:1\n\n\"The Logos became flesh and made his dwelling among us.\" — John 1:14\n\nJesus IS the Logos — God's eternal Word made flesh. When you read Scripture, you're not just reading a book. You're encountering a Person.",
    hashtags: "#LivingWater #WordStudy #Logos #TheWord #John1 #GreekWord #Jesus #BiblicalGreek #Theology",
    bibleRef: "John 1:1, 14",
  },

  // === APRIL 16 (Thursday) ===
  {
    id: "apr-16-verse",
    date: "2026-04-16",
    title: "Verse of the Day: Fruit of the Spirit",
    series: "Daily Verse of the Day",
    category: "quotes",
    platform: "both",
    description: "The full Galatians 5 fruit list. Colorful card.",
    caption: "The evidence of the Holy Spirit in your life:\n\n\"But the fruit of the Spirit is love, joy, peace, patience, kindness, goodness, faithfulness, gentleness and self-control.\" — Galatians 5:22-23\n\nWhich one is God growing in you right now?",
    hashtags: "#LivingWater #VerseOfTheDay #Galatians5 #FruitOfTheSpirit #HolySpirit #ChristianLiving",
    bibleRef: "Galatians 5:22-23",
  },
  {
    id: "apr-16-fruit",
    date: "2026-04-16",
    title: "Fruit of the Spirit: Joy",
    series: "Fruit of the Spirit Series",
    category: "devotionals",
    platform: "both",
    description: "Part 2 — JOY. Not happiness based on circumstances, but deep gladness rooted in God.",
    caption: "FRUIT OF THE SPIRIT: JOY (Part 2/9)\n\n\"...joy...\" — Galatians 5:22\n\nJoy is not happiness. Happiness depends on what happens. Joy depends on who God is.\n\nPaul wrote about joy from a prison cell (Philippians). Habakkuk sang for joy when the harvest failed (Hab 3:17-18).\n\nBiblical joy says: \"Even though life is hard, God is still good.\"\n\n\"The joy of the Lord is your strength.\" — Nehemiah 8:10\n\nJoy isn't the absence of pain — it's the presence of God in the midst of it.",
    hashtags: "#LivingWater #FruitOfTheSpirit #Joy #Galatians5 #Nehemiah8 #ChristianJoy #SpiritualGrowth",
    bibleRef: "Nehemiah 8:10",
  },

  // === APRIL 17 (Friday) ===
  {
    id: "apr-17-verse",
    date: "2026-04-17",
    title: "Verse of the Day: God Will Supply",
    series: "Daily Verse of the Day",
    category: "quotes",
    platform: "both",
    description: "Provision verse. Warm, reassuring.",
    caption: "Stop worrying about tomorrow. Your Provider is already there.\n\n\"And my God will meet all your needs according to the riches of his glory in Christ Jesus.\" — Philippians 4:19\n\nHe's never been late. He's never run out. He knows exactly what you need.",
    hashtags: "#LivingWater #VerseOfTheDay #Philippians4 #GodsProvision #TrustGod #BibleVerse #Faith",
    bibleRef: "Philippians 4:19",
  },
  {
    id: "apr-17-visual",
    date: "2026-04-17",
    title: "Verse + Visual: The Lord Is My Light",
    series: "Verse + Visual Quote Card",
    category: "creative",
    platform: "both",
    description: "Beautiful graphic design — sunrise/light imagery with Psalm 27:1. Canva-style verse card.",
    caption: "\"The Lord is my light and my salvation — whom shall I fear? The Lord is the stronghold of my life — of whom shall I be afraid?\" — Psalm 27:1\n\nSave this for those moments when fear tries to creep in.\n\nYou are held by the Light of the world.",
    hashtags: "#LivingWater #VerseCard #Psalm27 #Light #NeverAfraid #BibleVerse #ChristianArt",
    bibleRef: "Psalm 27:1",
  },

  // === APRIL 18 (Saturday) ===
  {
    id: "apr-18-verse",
    date: "2026-04-18",
    title: "Verse of the Day: Delight in the Lord",
    series: "Daily Verse of the Day",
    category: "quotes",
    platform: "both",
    description: "Weekend verse about delighting in God.",
    caption: "When your desire is Him — He gives you the desires of your heart.\n\n\"Delight yourself in the Lord, and He will give you the desires of your heart.\" — Psalm 37:4\n\nThis isn't a formula — it's a relationship. When you delight in Him, your desires align with His.",
    hashtags: "#LivingWater #VerseOfTheDay #Psalm37 #DelightInTheLord #Faith #BibleVerse",
    bibleRef: "Psalm 37:4",
  },
  {
    id: "apr-18-psalm",
    date: "2026-04-18",
    title: "Psalms Spotlight: Psalm 139 — Fearfully & Wonderfully Made",
    series: "Psalms Spotlight",
    category: "quotes",
    platform: "both",
    description: "Psalm 139 — God's intimate knowledge of us. Identity and worth.",
    caption: "PSALM SPOTLIGHT: Psalm 139\n\n\"I praise you because I am fearfully and wonderfully made; your works are wonderful, I know that full well.\" — Psalm 139:14\n\nGod formed you in the womb. He knows your thoughts before you think them. He's counted every hair on your head.\n\nYou are not an accident. You are not a mistake. You are a masterpiece — handcrafted by the Creator of the universe.\n\n\"Where can I go from your Spirit? Where can I flee from your presence?\" — Psalm 139:7\n\nNowhere. And that's the most comforting truth you'll hear today.",
    hashtags: "#LivingWater #PsalmSpotlight #Psalm139 #FearfullyMade #Identity #GodsLove #YouAreLoved",
    bibleRef: "Psalm 139:14",
  },

  // === APRIL 19 (Sunday) ===
  {
    id: "apr-19-verse",
    date: "2026-04-19",
    title: "Verse of the Day: Let Everything Praise",
    series: "Daily Verse of the Day",
    category: "quotes",
    platform: "both",
    description: "Sunday worship verse. Celebratory.",
    caption: "This is your Sunday reminder:\n\n\"Let everything that has breath praise the Lord. Praise the Lord!\" — Psalm 150:6\n\nYou're breathing. That means you have reason to praise Him today.",
    hashtags: "#LivingWater #VerseOfTheDay #Psalm150 #Praise #Worship #Sunday #BibleVerse",
    bibleRef: "Psalm 150:6",
  },
  {
    id: "apr-19-memory",
    date: "2026-04-19",
    title: "Scripture Memory Check-In + New Verse",
    series: "Scripture Memory Challenge",
    category: "engagement",
    platform: "both",
    description: "Check in on last week's verse (Romans 8:28). Give new verse: Philippians 4:13.",
    caption: "SCRIPTURE MEMORY CHECK-IN\n\nDid you memorize Romans 8:28 this week? Drop it in the comments from memory!\n\n\"And we know that in all things God works for the good of those who love Him, who have been called according to His purpose.\"\n\nNEW VERSE for this week:\n\n\"I can do all things through Christ who strengthens me.\" — Philippians 4:13\n\nComment \"I'M IN\" if you're taking this week's challenge!",
    hashtags: "#LivingWater #ScriptureMemory #Philippians413 #BibleChallenge #MemorizeScripture #Community",
    bibleRef: "Philippians 4:13",
  },

  // === APRIL 20 (Monday) ===
  {
    id: "apr-20-verse",
    date: "2026-04-20",
    title: "Verse of the Day: Seek First the Kingdom",
    series: "Daily Verse of the Day",
    category: "quotes",
    platform: "both",
    description: "Priority verse for the start of the week.",
    caption: "New week, same priority:\n\n\"But seek first His kingdom and His righteousness, and all these things will be given to you as well.\" — Matthew 6:33\n\nPut God first this week. Everything else will fall into place.",
    hashtags: "#LivingWater #VerseOfTheDay #Matthew6 #SeekFirst #KingdomOfGod #Monday #Faith",
    bibleRef: "Matthew 6:33",
  },
  {
    id: "apr-20-gospel",
    date: "2026-04-20",
    title: "Good News Monday: Jesus Died for You Personally",
    series: "Good News Monday",
    category: "devotionals",
    platform: "both",
    description: "Personal angle on the Gospel. Not just for the world — for YOU.",
    caption: "GOOD NEWS MONDAY\n\nJesus didn't just die for \"the world.\" He died for YOU.\n\n\"The Son of God, who loved ME and gave Himself for ME.\" — Galatians 2:20\n\nPaul made it personal. So should you.\n\nIf you were the only person on earth, Jesus would have still gone to the cross — just for you.\n\nThat's how much you're worth to Him.",
    hashtags: "#LivingWater #GoodNewsMonday #Galatians2 #PersonalGospel #JesusDiedForMe #GoodNews",
    bibleRef: "Galatians 2:20",
  },

  // === APRIL 21 (Tuesday) ===
  {
    id: "apr-21-verse",
    date: "2026-04-21",
    title: "Verse of the Day: Love One Another",
    series: "Daily Verse of the Day",
    category: "quotes",
    platform: "both",
    description: "Jesus' command to love. Simple and direct.",
    caption: "The clearest command Jesus gave:\n\n\"A new command I give you: Love one another. As I have loved you, so you must love one another.\" — John 13:34\n\nHow has Jesus loved you? Sacrificially. Unconditionally. Endlessly.\n\nGo and do the same.",
    hashtags: "#LivingWater #VerseOfTheDay #John13 #LoveOneAnother #JesusCommand #BibleVerse",
    bibleRef: "John 13:34",
  },
  {
    id: "apr-21-testimony",
    date: "2026-04-21",
    title: "Testimony Tuesday: David — A Man After God's Heart",
    series: "Testimony Tuesday",
    category: "stories",
    platform: "both",
    description: "David's story — shepherd, warrior, sinner, worshipper. God uses broken people.",
    caption: "TESTIMONY TUESDAY: David\n\nShepherd boy. Giant killer. King. Adulterer. Murderer. Worshipper.\n\nDavid's life was messy. He made terrible mistakes. But here's what God said about him:\n\n\"I have found David son of Jesse, a man after my own heart; he will do everything I want him to do.\" — Acts 13:22\n\nWhat made David different wasn't perfection — it was repentance. Every time he fell, he ran BACK to God, not away.\n\n\"Create in me a clean heart, O God.\" — Psalm 51:10\n\nGod doesn't need your perfection. He wants your heart.",
    hashtags: "#LivingWater #TestimonyTuesday #David #ManAfterGodsHeart #Psalm51 #Repentance #Grace",
    bibleRef: "Acts 13:22",
  },

  // === APRIL 22 (Wednesday) ===
  {
    id: "apr-22-verse",
    date: "2026-04-22",
    title: "Verse of the Day: His Mercies Are New",
    series: "Daily Verse of the Day",
    category: "quotes",
    platform: "both",
    description: "Morning mercy verse. Sunrise tones.",
    caption: "Every single morning, He gives you a fresh start.\n\n\"Because of the Lord's great love we are not consumed, for His compassions never fail. They are new every morning; great is your faithfulness.\" — Lamentations 3:22-23\n\nYesterday's failures don't carry into today. His mercy resets at dawn.",
    hashtags: "#LivingWater #VerseOfTheDay #Lamentations3 #NewMercies #Faithfulness #Morning #BibleVerse",
    bibleRef: "Lamentations 3:22-23",
  },
  {
    id: "apr-22-word",
    date: "2026-04-22",
    title: "Word Study: Charis (Grace)",
    series: "Word Study Wednesday",
    category: "devotionals",
    platform: "both",
    description: "Greek word 'Charis' — grace, unmerited favor. The foundation of the Gospel.",
    caption: "WORD STUDY: CHARIS\n\nThe Greek word 'Charis' (χάρις) means grace — unearned, undeserved favor.\n\nIt's the word Paul uses more than any other to describe how God saves us:\n\n\"For it is by charis you have been saved, through faith — and this is not from yourselves, it is the gift of God.\" — Ephesians 2:8\n\nGrace means:\n- You can't earn it\n- You don't deserve it\n- You can't lose it\n- It's freely given\n\nGrace is God giving you what you need instead of what you deserve. And it changes everything.",
    hashtags: "#LivingWater #WordStudy #Charis #Grace #GreekWord #Ephesians2 #Gospel #ChristianTeaching",
    bibleRef: "Ephesians 2:8",
  },

  // === APRIL 23 (Thursday) ===
  {
    id: "apr-23-verse",
    date: "2026-04-23",
    title: "Verse of the Day: Nothing Can Separate Us",
    series: "Daily Verse of the Day",
    category: "quotes",
    platform: "both",
    description: "Romans 8 promise. Bold, confident design.",
    caption: "Read this slowly:\n\n\"Neither death nor life, neither angels nor demons, neither the present nor the future, nor any powers, neither height nor depth, nor anything else in all creation, will be able to separate us from the love of God that is in Christ Jesus our Lord.\" — Romans 8:38-39\n\nNOTHING. Absolutely nothing.",
    hashtags: "#LivingWater #VerseOfTheDay #Romans8 #GodsLove #NothingCanSeparate #BibleVerse #Secure",
    bibleRef: "Romans 8:38-39",
  },
  {
    id: "apr-23-fruit",
    date: "2026-04-23",
    title: "Fruit of the Spirit: Peace",
    series: "Fruit of the Spirit Series",
    category: "devotionals",
    platform: "both",
    description: "Part 3 — PEACE. Not the absence of storms, but the presence of God in the storm.",
    caption: "FRUIT OF THE SPIRIT: PEACE (Part 3/9)\n\n\"...peace...\" — Galatians 5:22\n\nJesus was sleeping in a boat during a storm. The disciples panicked. He woke up and said: \"Peace, be still.\" (Mark 4:39)\n\nBiblical peace isn't the absence of trouble — it's the presence of Jesus in the middle of it.\n\n\"Peace I leave with you; my peace I give you. I do not give to you as the world gives.\" — John 14:27\n\nThe world's peace depends on circumstances. God's peace surpasses understanding (Phil 4:7).\n\nLet His peace guard your heart today.",
    hashtags: "#LivingWater #FruitOfTheSpirit #Peace #Galatians5 #John14 #InnerPeace #ChristianLiving",
    bibleRef: "John 14:27",
  },

  // === APRIL 24 (Friday) ===
  {
    id: "apr-24-verse",
    date: "2026-04-24",
    title: "Verse of the Day: I Am the Way",
    series: "Daily Verse of the Day",
    category: "quotes",
    platform: "both",
    description: "Jesus' bold declaration. Clean red-letter design.",
    caption: "Jesus didn't say He would SHOW the way. He said He IS the way.\n\n\"I am the way and the truth and the life. No one comes to the Father except through me.\" — John 14:6\n\nNot a way. THE Way.",
    hashtags: "#LivingWater #VerseOfTheDay #John14 #TheWay #Jesus #Truth #Life #BibleVerse",
    bibleRef: "John 14:6",
  },
  {
    id: "apr-24-prayer",
    date: "2026-04-24",
    title: "Prayer Request Thread",
    series: "Prayer Request Thread",
    category: "engagement",
    platform: "both",
    description: "Weekly prayer request post. Invite followers to share requests. Respond with prayers.",
    caption: "PRAYER REQUEST THREAD\n\nDrop your prayer request below. Our community will pray with you and for you.\n\nNo request is too big or too small. God hears every word.\n\n\"Do not be anxious about anything, but in every situation, by prayer and petition, with thanksgiving, present your requests to God.\" — Philippians 4:6\n\nYou are not alone. We are praying.",
    hashtags: "#LivingWater #PrayerRequest #PrayerThread #WePray #Community #Philippians4 #Prayer",
    bibleRef: "Philippians 4:6",
  },

  // === APRIL 25 (Saturday) ===
  {
    id: "apr-25-verse",
    date: "2026-04-25",
    title: "Verse of the Day: Be Strong and Courageous",
    series: "Daily Verse of the Day",
    category: "quotes",
    platform: "both",
    description: "Joshua's commission. Bold, encouraging.",
    caption: "God said this to Joshua. He's saying it to you today:\n\n\"Be strong and courageous. Do not be afraid; do not be discouraged, for the Lord your God will be with you wherever you go.\" — Joshua 1:9\n\nWherever. You. Go. He's there.",
    hashtags: "#LivingWater #VerseOfTheDay #Joshua1 #BeStrong #Courage #GodsPresence #BibleVerse",
    bibleRef: "Joshua 1:9",
  },
  {
    id: "apr-25-psalm",
    date: "2026-04-25",
    title: "Psalms Spotlight: Psalm 23 — The Good Shepherd",
    series: "Psalms Spotlight",
    category: "quotes",
    platform: "both",
    description: "Full Psalm 23 devotional. The most beloved Psalm.",
    caption: "PSALM SPOTLIGHT: Psalm 23\n\n\"The Lord is my shepherd, I lack nothing.\nHe makes me lie down in green pastures,\nHe leads me beside quiet waters,\nHe refreshes my soul.\"\n\nThis Psalm has comforted millions for 3,000 years. Why? Because it reminds us:\n\n- He provides (\"I lack nothing\")\n- He leads (\"beside quiet waters\")\n- He restores (\"refreshes my soul\")\n- He protects (\"valley of the shadow of death\")\n- He blesses (\"my cup overflows\")\n\n\"Surely goodness and love will follow me all the days of my life.\" — Psalm 23:6\n\nYou are shepherded by the King of Kings.",
    hashtags: "#LivingWater #PsalmSpotlight #Psalm23 #GoodShepherd #GodsProvision #Comfort #BibleStudy",
    bibleRef: "Psalm 23",
  },

  // === APRIL 26 (Sunday) ===
  {
    id: "apr-26-verse",
    date: "2026-04-26",
    title: "Verse of the Day: With God All Things Are Possible",
    series: "Daily Verse of the Day",
    category: "quotes",
    platform: "both",
    description: "Sunday hope verse.",
    caption: "Whatever you think is impossible:\n\n\"With man this is impossible, but with God all things are possible.\" — Matthew 19:26\n\nYour impossibility is God's opportunity.",
    hashtags: "#LivingWater #VerseOfTheDay #Matthew19 #AllThingsPossible #Faith #Sunday #Hope",
    bibleRef: "Matthew 19:26",
  },
  {
    id: "apr-26-learned",
    date: "2026-04-26",
    title: "This Week I Learned: God's Timing Is Perfect",
    series: "This Week I Learned",
    category: "engagement",
    platform: "both",
    description: "Reflective post sharing a spiritual lesson. Invite followers to share theirs.",
    caption: "THIS WEEK I LEARNED...\n\nGod's timing doesn't always match mine — and that's okay.\n\nThis week I was reminded that waiting on God isn't wasted time. He's always preparing something better than what I planned.\n\n\"He has made everything beautiful in its time.\" — Ecclesiastes 3:11\n\nWhat's something God taught you this week? Share below!",
    hashtags: "#LivingWater #ThisWeekILearned #GodsTiming #Ecclesiastes3 #SpiritualGrowth #Community",
    bibleRef: "Ecclesiastes 3:11",
  },

  // === APRIL 27 (Monday) ===
  {
    id: "apr-27-verse",
    date: "2026-04-27",
    title: "Verse of the Day: Philippians 4:13",
    series: "Daily Verse of the Day",
    category: "quotes",
    platform: "both",
    description: "Strength through Christ. Clean, bold.",
    caption: "Not in your strength. In His.\n\n\"I can do all things through Christ who strengthens me.\" — Philippians 4:13\n\nThis verse isn't about doing anything you want. It's about doing everything God calls you to — because His power is in you.",
    hashtags: "#LivingWater #VerseOfTheDay #Philippians413 #ChristStrengthensMe #Faith #BibleVerse",
    bibleRef: "Philippians 4:13",
  },
  {
    id: "apr-27-gospel",
    date: "2026-04-27",
    title: "Good News Monday: You Are Forgiven",
    series: "Good News Monday",
    category: "devotionals",
    platform: "both",
    description: "Focus on forgiveness. The guilt you carry has already been paid for.",
    caption: "GOOD NEWS MONDAY\n\nThat thing you did that keeps you up at night? That shame you carry?\n\nJesus already paid for it.\n\n\"If we confess our sins, He is faithful and just and will forgive us our sins and purify us from all unrighteousness.\" — 1 John 1:9\n\nYou don't need to earn forgiveness. You just need to receive it.\n\nToday, let go of the guilt. He already let go of the sin.",
    hashtags: "#LivingWater #GoodNewsMonday #Forgiveness #1John1 #Grace #FreedomInChrist #GoodNews",
    bibleRef: "1 John 1:9",
  },

  // === APRIL 28 (Tuesday) ===
  {
    id: "apr-28-verse",
    date: "2026-04-28",
    title: "Verse of the Day: Cast Your Cares",
    series: "Daily Verse of the Day",
    category: "quotes",
    platform: "both",
    description: "Anxiety relief verse. Soft, calming design.",
    caption: "Whatever is weighing on you — hand it over.\n\n\"Cast all your anxiety on Him because He cares for you.\" — 1 Peter 5:7\n\nHe doesn't just tolerate your burdens. He wants them. Because He cares for YOU.",
    hashtags: "#LivingWater #VerseOfTheDay #1Peter5 #CastYourCares #Anxiety #GodsLove #BibleVerse",
    bibleRef: "1 Peter 5:7",
  },
  {
    id: "apr-28-testimony",
    date: "2026-04-28",
    title: "Testimony Tuesday: Esther — For Such a Time as This",
    series: "Testimony Tuesday",
    category: "stories",
    platform: "both",
    description: "Esther's story — an orphan girl who saved a nation. God's providential timing.",
    caption: "TESTIMONY TUESDAY: Esther\n\nShe was an orphan. A foreigner. A woman in a man's world.\n\nBut God placed her exactly where she needed to be.\n\nWhen her people faced destruction, Mordecai told her:\n\n\"Who knows whether you have not come to the kingdom for such a time as this?\" — Esther 4:14\n\nEsther risked her life. She approached the king uninvited. And God used her to save an entire nation.\n\nMaybe you feel like you don't belong. Maybe you feel small. But God has placed you exactly where you are — for such a time as this.",
    hashtags: "#LivingWater #TestimonyTuesday #Esther #ForSuchATime #GodsProvidence #BibleStory #Purpose",
    bibleRef: "Esther 4:14",
  },

  // === APRIL 29 (Wednesday) ===
  {
    id: "apr-29-verse",
    date: "2026-04-29",
    title: "Verse of the Day: Great Is Thy Faithfulness",
    series: "Daily Verse of the Day",
    category: "quotes",
    platform: "both",
    description: "Faithfulness verse. Classic hymn connection.",
    caption: "He has never failed you. He never will.\n\n\"The steadfast love of the Lord never ceases; His mercies never come to an end; they are new every morning; great is your faithfulness.\" — Lamentations 3:22-23 (ESV)\n\nGreat is Thy faithfulness, O God my Father.",
    hashtags: "#LivingWater #VerseOfTheDay #Lamentations3 #GreatIsThy Faithfulness #GodsLove #BibleVerse",
    bibleRef: "Lamentations 3:22-23",
  },
  {
    id: "apr-29-word",
    date: "2026-04-29",
    title: "Word Study: Agape (Unconditional Love)",
    series: "Word Study Wednesday",
    category: "devotionals",
    platform: "both",
    description: "Greek word 'Agape' — the highest form of love. God's love for us.",
    caption: "WORD STUDY: AGAPE\n\nThe Greek word 'Agape' (ἀγάπη) is the highest form of love in the Bible.\n\nGreek has 4 words for love:\n- Eros (romantic)\n- Philia (friendship)\n- Storge (family)\n- Agape (unconditional, sacrificial)\n\nAgape is the love God has for you:\n\n\"God demonstrates His own agape for us in this: While we were still sinners, Christ died for us.\" — Romans 5:8\n\nAgape doesn't wait for you to be lovable. It loves you at your worst. It loves you first. That's God's love.",
    hashtags: "#LivingWater #WordStudy #Agape #UnconditionalLove #GreekWord #Romans5 #GodsLove #Theology",
    bibleRef: "Romans 5:8",
  },

  // === APRIL 30 (Thursday) ===
  {
    id: "apr-30-verse",
    date: "2026-04-30",
    title: "Verse of the Day: The Lord Bless You",
    series: "Daily Verse of the Day",
    category: "quotes",
    platform: "both",
    description: "End the month with the priestly blessing. Beautiful, warm send-off.",
    caption: "As we close this month, receive this blessing:\n\n\"The Lord bless you and keep you; the Lord make His face shine on you and be gracious to you; the Lord turn His face toward you and give you peace.\" — Numbers 6:24-26\n\nMay God's face shine on you this month and always.",
    hashtags: "#LivingWater #VerseOfTheDay #Numbers6 #Blessing #AaronicBlessing #Peace #EndOfMonth",
    bibleRef: "Numbers 6:24-26",
  },
  {
    id: "apr-30-fruit",
    date: "2026-04-30",
    title: "Fruit of the Spirit: Patience",
    series: "Fruit of the Spirit Series",
    category: "devotionals",
    platform: "both",
    description: "Part 4 — PATIENCE. God's patient love and our call to reflect it.",
    caption: "FRUIT OF THE SPIRIT: PATIENCE (Part 4/9)\n\n\"...patience...\" — Galatians 5:22\n\nPatience is love under pressure. It's choosing kindness when everything in you wants to react.\n\nGod is the ultimate model:\n\n\"The Lord is slow to anger, abounding in love.\" — Psalm 103:8\n\nHe has been so patient with us. How much more should we be patient with others?\n\nPractical step: Next time someone frustrates you this week, pause. Breathe. Remember how patient God has been with you. Then respond — don't react.",
    hashtags: "#LivingWater #FruitOfTheSpirit #Patience #Galatians5 #Psalm103 #ChristianLiving #SpiritualGrowth",
    bibleRef: "Psalm 103:8",
  },

  // === BONUS: Answered Prayer Spotlight (mid-month) ===
  {
    id: "apr-15-answered",
    date: "2026-04-15",
    title: "Answered Prayer Spotlight",
    series: "Answered Prayer Spotlight",
    category: "stories",
    platform: "instagram",
    description: "Invite followers to share answered prayers. Repost stories with permission. Instagram Stories format.",
    caption: "ANSWERED PRAYER SPOTLIGHT\n\nHas God answered a prayer for you recently? We want to celebrate with you!\n\nShare your answered prayer in the comments or DM us — with your permission, we'll share it to encourage others.\n\n\"The prayer of a righteous person is powerful and effective.\" — James 5:16\n\nGod is still in the business of answering prayers. Let's praise Him together!",
    hashtags: "#LivingWater #AnsweredPrayer #Testimony #James5 #GodAnswers #PraiseReport #ChristianCommunity",
    bibleRef: "James 5:16",
  },

  // === Names of God (weekly) ===
  {
    id: "apr-05-name",
    date: "2026-04-05",
    title: "Names of God: Jehovah Jireh — The Lord Will Provide",
    series: "Names of God Series",
    category: "quotes",
    platform: "both",
    description: "Easter connection — God provided the ultimate sacrifice. Deep teaching post.",
    caption: "NAMES OF GOD: JEHOVAH JIREH\n\n\"The Lord Will Provide\" — Genesis 22:14\n\nWhen Abraham was about to sacrifice Isaac, God provided a ram instead. Abraham named that place \"Jehovah Jireh\" — the Lord will provide.\n\nOn Easter, God provided the ultimate sacrifice — His own Son.\n\nJehovah Jireh didn't just provide a ram on a mountain. He provided a Savior on a cross.\n\nWhatever you need today, trust Jehovah Jireh. He has already provided.",
    hashtags: "#LivingWater #NamesOfGod #JehovahJireh #Provider #Genesis22 #Easter #HebrewNames",
    bibleRef: "Genesis 22:14",
  },
  {
    id: "apr-12-name",
    date: "2026-04-12",
    title: "Names of God: El Shaddai — God Almighty",
    series: "Names of God Series",
    category: "quotes",
    platform: "both",
    description: "El Shaddai — the all-sufficient, almighty God. Nothing is too hard for Him.",
    caption: "NAMES OF GOD: EL SHADDAI\n\n\"God Almighty\" — Genesis 17:1\n\nWhen God appeared to Abraham at age 99 and promised him a son, He introduced Himself as El Shaddai — God Almighty.\n\nEl Shaddai means: all-powerful, all-sufficient, more than enough.\n\nIs there something in your life that seems impossible? El Shaddai says:\n\n\"Is anything too hard for the Lord?\" — Genesis 18:14\n\nNothing. The answer is nothing.",
    hashtags: "#LivingWater #NamesOfGod #ElShaddai #GodAlmighty #Genesis17 #HebrewNames #NothingImpossible",
    bibleRef: "Genesis 17:1",
  },
  {
    id: "apr-19-name",
    date: "2026-04-19",
    title: "Names of God: Jehovah Rapha — The Lord Who Heals",
    series: "Names of God Series",
    category: "quotes",
    platform: "both",
    description: "God as Healer — physical, emotional, spiritual healing.",
    caption: "NAMES OF GOD: JEHOVAH RAPHA\n\n\"The Lord Who Heals\" — Exodus 15:26\n\nAfter leading Israel through the Red Sea, God revealed Himself as Jehovah Rapha — the God who heals.\n\n\"He heals the brokenhearted and binds up their wounds.\" — Psalm 147:3\n\nGod doesn't just heal bodies. He heals hearts. He heals memories. He heals what you thought was beyond repair.\n\nBring your brokenness to Jehovah Rapha today.",
    hashtags: "#LivingWater #NamesOfGod #JehovahRapha #Healer #Exodus15 #Psalm147 #Healing #GodsNames",
    bibleRef: "Exodus 15:26",
  },
  {
    id: "apr-26-name",
    date: "2026-04-26",
    title: "Names of God: Jehovah Shalom — The Lord Is Peace",
    series: "Names of God Series",
    category: "quotes",
    platform: "both",
    description: "God as our peace. In a chaotic world, He is Shalom.",
    caption: "NAMES OF GOD: JEHOVAH SHALOM\n\n\"The Lord Is Peace\" — Judges 6:24\n\nGideon was hiding in a winepress, terrified. God called him a \"mighty warrior.\" When Gideon realized he'd seen the angel of the Lord, he was afraid — but God said: \"Peace! Do not be afraid.\"\n\nGideon built an altar and named it Jehovah Shalom — The Lord Is Peace.\n\nIn your fear, in your chaos, in your anxiety — God's name over your life is PEACE.\n\n\"You will keep in perfect peace those whose minds are steadfast, because they trust in you.\" — Isaiah 26:3",
    hashtags: "#LivingWater #NamesOfGod #JehovahShalom #Peace #Judges6 #Isaiah26 #GodsNames #Trust",
    bibleRef: "Judges 6:24",
  },
];

export default APRIL_2026;

export const CATEGORY_COLORS: Record<ContentCategory, string> = {
  quotes: "bg-gold-100 text-gold-800 border-gold-300",
  stories: "bg-rose-100 text-rose-800 border-rose-300",
  devotionals: "bg-navy-100 text-navy-800 border-navy-300",
  engagement: "bg-emerald-100 text-emerald-800 border-emerald-300",
  creative: "bg-purple-100 text-purple-800 border-purple-300",
};

export const CATEGORY_DOT_COLORS: Record<ContentCategory, string> = {
  quotes: "bg-gold-400",
  stories: "bg-rose-400",
  devotionals: "bg-navy-400",
  engagement: "bg-emerald-400",
  creative: "bg-purple-400",
};

export const SERIES_LIST = [
  "Daily Verse of the Day",
  "Names of God Series",
  "Psalms Spotlight",
  "Testimony Tuesday",
  "Biblical Character Series",
  "Answered Prayer Spotlight",
  "Good News Monday",
  "Word Study Wednesday",
  "Fruit of the Spirit Series",
  "Scripture Memory Challenge",
  "Prayer Request Thread",
  "This Week I Learned",
  "Verse + Visual Quote Card",
  "Worship Song Reflection",
  "Seasonal Devotional Series",
];
